name: 'Airmeet Github Action'
description: 'Foundation for CI/CD on Github Action'
inputs:
  OPERATION:
    description: 'The operation to perform'
    required: true
  ENVIRONMENT:
    description: 'The environment to deploy to'
    required: true
runs:
  using: 'docker'
  main: 'Dockerfile'