name: Approval

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'The environment to deploy to'     
        required: true
        options: 
        - Dev
        - Test
        - Pre-prod


jobs:
  approvals:
    runs-on: ubuntu-latest

    steps:
      - name: Create issue
        if: github.ref == 'refs/heads/release*' || github.ref == 'refs/heads/develop' 
        uses: JasonEtco/create-an-issue@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          RUN_NUMBER: ${{ github.run_number}}
        with:
          filename: .github/approvals.md
