name: Trigger Deployment

on:
  issue_comment:
    types: [created]

jobs:
  get-context:
    runs-on: ubuntu-latest
    steps:
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  get-environment:
    if: github.event.issue.label == 'deployment-requested'
    runs-on: ubuntu-latest
    steps:
      - name: Get environment
        run: echo "Triggering CodePipeline"

  parse-approvals:
    if: ${{ github.event.comment.body == 'Approved' || github.event.issue.pull_request == 'Approved' }}
  
    steps:
      - name: Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Deployment initiated"

  trigger-deployment:
    needs: [parse-approvals]
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CodePipeline
        if: ${{ needs.parse-approvals.result == 'success' }}
        run: echo "Triggering CodePipeline"

  close-issue:
    needs: [trigger-deployment]
    runs-on: ubuntu-latest

    steps:
      - name: Close Issue
        if: ${{ needs.trigger-deployment.result == 'success' }}
        uses: peter-evans/close-issue@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: "Deployment complete"