name: Context

on:
  issue_comment:
    types: [created]

jobs:

  issue_name:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue name
        if: ${{ github.event.issue.label == 'deployment-requested' &&  !github.event.issue.pull_request }}
        run: 'echo ${{ github.event.issue.body }}'